// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-WWtvVMqDYooA6cTmcbuwZTKa5zO-Zk',
    appId: '1:444716206318:web:5d766e282d696fc155cbff',
    messagingSenderId: '444716206318',
    projectId: 'cinetec-ac38d',
    authDomain: 'cinetec-ac38d.firebaseapp.com',
    storageBucket: 'cinetec-ac38d.firebasestorage.app',
    measurementId: 'G-BXT3XR5NLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANLVkQI2LLlPUyFaDOcmZoxZaxBBiVDPU',
    appId: '1:444716206318:android:031cab02e2a748cf55cbff',
    messagingSenderId: '444716206318',
    projectId: 'cinetec-ac38d',
    storageBucket: 'cinetec-ac38d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl-Ou38oeK_TGQEF2NlIneMQAVEeKzEYo',
    appId: '1:444716206318:ios:b8c55726ac50c11955cbff',
    messagingSenderId: '444716206318',
    projectId: 'cinetec-ac38d',
    storageBucket: 'cinetec-ac38d.firebasestorage.app',
    iosBundleId: 'com.example.cinetec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl-Ou38oeK_TGQEF2NlIneMQAVEeKzEYo',
    appId: '1:444716206318:ios:b8c55726ac50c11955cbff',
    messagingSenderId: '444716206318',
    projectId: 'cinetec-ac38d',
    storageBucket: 'cinetec-ac38d.firebasestorage.app',
    iosBundleId: 'com.example.cinetec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs-WWtvVMqDYooA6cTmcbuwZTKa5zO-Zk',
    appId: '1:444716206318:web:516b18c2fd5be09155cbff',
    messagingSenderId: '444716206318',
    projectId: 'cinetec-ac38d',
    authDomain: 'cinetec-ac38d.firebaseapp.com',
    storageBucket: 'cinetec-ac38d.firebasestorage.app',
    measurementId: 'G-2Z32E6LL4J',
  );
}
